# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73d4bd4a1d364ab4808179d0f4e8879974205d7a369bcec042c3a632ace92a65b84eb6908b4a556539ae06f5f975a16c39f01d8eb3cbedfc37dd3fc582fd2197

test:
  secret_key_base: 2d2ede5c8a213723b2125e1351a845118c7ff026389573521dd56a0fef89a058aca7c6555dc976656e3f352f3d67d2198f4c8cf550b4c9b2117945817eaa01b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
